port: /dev/ttyACM0
baud: 115200
timeout: 0.1

wheel_radius: 0.06 # m
base_width: 0.5 # m
counts_per_rev: 64.0
gear_ratio: 75.0
encoder_on_motor_shaft: 1 # 0 is false and 1 is true

pid_gains: [200,1,15]
control_rate: [50]
encoder_rate: [50]
pwm_range: [255]
no_cmd_timeout: [1]
publish_tf: true
